In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import LabelEncoder

In [106]:
df6=pd.read_csv('BrandEDA.csv')
df6.head()

Brand  Item ID Ram(Gb)  StoraGe(Gb)  Price(Rs)  Processor speed(GHz)  \
0  Apple       32      16        256.0     315000                   2.2   
1  Apple        8       8        512.0     232000                   3.2   
2  Apple       32      16       1024.0     382000                   2.3   
3  Apple       26       8          NaN     195000                   2.3   
4  Apple       32       4        128.0      92400                   1.8   

   Touch       Color   Weight  DisplAy size(Inch)  
0      No  Space grey    1.83                15.4  
1      No  Dark Black    1.29                13.3  
2      No      Silver    2.00                16.0  
3      No  Space grey    1.37                13.3  
4      No      Silver    1.35                11.6

Check the number of rows and columns

In [107]:
df6.shape

(30, 10)

Check the columns

In [108]:
df6.columns

Index(['Brand', 'Item ID', 'Ram(Gb)', 'StoraGe(Gb)', 'Price(Rs)',
       'Processor speed(GHz)', ' Touch ', 'Color ', 'Weight',
       'DisplAy size(Inch)'],
      dtype='object')

analysing the brand based on the price
Challenges:
1)Find NaN data

In [109]:
df6.isna().sum()

Brand                   0
Item ID                 0
Ram(Gb)                 1
StoraGe(Gb)             2
Price(Rs)               0
Processor speed(GHz)    0
 Touch                  0
Color                   0
Weight                  3
DisplAy size(Inch)      0
dtype: int64

Dropping the NaN's there are very few Nan's

In [110]:
df6.dropna()
df6.head()

Brand  Item ID Ram(Gb)  StoraGe(Gb)  Price(Rs)  Processor speed(GHz)  \
0  Apple       32      16        256.0     315000                   2.2   
1  Apple        8       8        512.0     232000                   3.2   
2  Apple       32      16       1024.0     382000                   2.3   
3  Apple       26       8          NaN     195000                   2.3   
4  Apple       32       4        128.0      92400                   1.8   

   Touch       Color   Weight  DisplAy size(Inch)  
0      No  Space grey    1.83                15.4  
1      No  Dark Black    1.29                13.3  
2      No      Silver    2.00                16.0  
3      No  Space grey    1.37                13.3  
4      No      Silver    1.35                11.6

In [111]:
df6.isna().sum()

Brand                   0
Item ID                 0
Ram(Gb)                 1
StoraGe(Gb)             2
Price(Rs)               0
Processor speed(GHz)    0
 Touch                  0
Color                   0
Weight                  3
DisplAy size(Inch)      0
dtype: int64

Filling the NaN's using LabelEncoder

In [112]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df6['Ram(Gb)'] = le.fit_transform(df6['Ram(Gb)'])
df6['StoraGe(Gb)'] = le.fit_transform(df6['StoraGe(Gb)'])
df6['Weight'] = le.fit_transform(df6['Weight'])


In [113]:
df6['Ram(Gb)'].isna().sum()

0

In [114]:
df6['StoraGe(Gb)'].isna().sum()

0

In [115]:
df6['Weight'].isna().sum()

0

In [116]:
df6.isna().sum()

Brand                   0
Item ID                 0
Ram(Gb)                 0
StoraGe(Gb)             0
Price(Rs)               0
Processor speed(GHz)    0
 Touch                  0
Color                   0
Weight                  0
DisplAy size(Inch)      0
dtype: int64

Few column names having space in the end hence removing the space 

In [119]:
df6.columns = df5.columns.str.replace(' ', '')
df6.columns

Index(['Brand', 'ItemID', 'Ram(Gb)', 'StoraGe(Gb)', 'Price(Rs)',
       'Processorspeed(GHz)', 'Touch', 'Color', 'Weight', 'DisplAysize(Inch)'],
      dtype='object')

Checking unique data of Touch to replace the categorical columns to numerical

In [120]:
df6.Touch

0      No
1      No
2      No
3      No
4      No
5      No
6      No
7      No
8      No
9      No
10     No
11     No
12     No
13    Yes
14    Yes
15    Yes
16     No
17     No
18    Yes
19     No
20     No
21     No
22     No
23     No
24     No
25     No
26     No
27     No
28     No
29     No
Name: Touch, dtype: object

In [121]:
df6.Touch=df6.Touch.map({'No':0,'Yes':1})
df6.Touch[:3]

0    0
1    0
2    0
Name: Touch, dtype: int64

In [122]:
df6.Color.unique()

array(['Space grey', 'Dark Black', 'Silver', 'Rose Gold', 'Black',
       'White'], dtype=object)

In [124]:
X = df6.iloc[:,1:]
y = df6['Brand']

In [123]:
df6.Color=df6.Color.map({'Space grey':00, 'Dark Black':11, 'Silver':22, 'Rose Gold':33, 'Black':44,'White':55})
df6.Color

0      0
1     11
2     22
3      0
4     22
5     22
6     22
7     22
8     33
9     22
10    44
11    44
12    44
13    22
14    22
15    22
16    22
17    22
18    22
19    44
20    22
21    22
22    22
23    22
24    33
25    44
26    44
27    44
28    55
29    44
Name: Color, dtype: int64

In [125]:
X.head()

ItemID  Ram(Gb)  StoraGe(Gb)  Price(Rs)  Processorspeed(GHz)  Touch  Color  \
0      32        2            2     315000                  2.2      0      0   
1       8        5            4     232000                  3.2      0     11   
2      32        2            6     382000                  2.3      0     22   
3      26        5            7     195000                  2.3      0      0   
4      32        3            0      92400                  1.8      0     22   

   Weight  DisplAysize(Inch)  
0      13               15.4  
1       6               13.3  
2      16               16.0  
3       8               13.3  
4       7               11.6

In [126]:
y.head()

0    Apple
1    Apple
2    Apple
3    Apple
4    Apple
Name: Brand, dtype: object

In [127]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [128]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [129]:
sfm = SelectFromModel(rf_model, threshold='median')
sfm.fit(X_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(random_state=42),
                threshold='median')

In [130]:
selected_features = X_train.columns[sfm.get_support()]

# Display selected features
print("Selected Features:", selected_features)

Selected Features: Index(['Price(Rs)', 'Touch', 'Color', 'Weight', 'DisplAysize(Inch)'], dtype='object')


In [131]:
X_train_selected = sfm.transform(X_train)
X_test_selected = sfm.transform(X_test)

In [132]:
X_train_selected

array([[3.320e+04, 0.000e+00, 5.500e+01, 2.000e+01, 1.560e+01],
       [1.400e+05, 0.000e+00, 3.300e+01, 7.000e+00, 1.200e+01],
       [1.000e+05, 0.000e+00, 4.400e+01, 1.100e+01, 1.560e+01],
       [3.150e+05, 0.000e+00, 0.000e+00, 1.300e+01, 1.540e+01],
       [9.240e+04, 0.000e+00, 2.200e+01, 7.000e+00, 1.160e+01],
       [1.850e+05, 0.000e+00, 2.200e+01, 4.000e+00, 1.330e+01],
       [6.000e+04, 0.000e+00, 2.200e+01, 2.000e+00, 1.330e+01],
       [1.250e+05, 1.000e+00, 2.200e+01, 1.400e+01, 1.560e+01],
       [9.000e+04, 0.000e+00, 4.400e+01, 1.200e+01, 1.560e+01],
       [2.000e+05, 0.000e+00, 2.200e+01, 1.300e+01, 1.540e+01],
       [2.320e+05, 0.000e+00, 1.100e+01, 6.000e+00, 1.330e+01],
       [3.820e+05, 0.000e+00, 2.200e+01, 1.600e+01, 1.600e+01],
       [1.700e+05, 0.000e+00, 4.400e+01, 1.800e+01, 1.560e+01],
       [1.950e+05, 0.000e+00, 0.000e+00, 8.000e+00, 1.330e+01],
       [1.010e+05, 0.000e+00, 2.200e+01, 2.100e+01, 1.100e+01],
       [2.500e+04, 0.000e+00, 4.400e+01,

In [133]:
rf_model.fit(X_train_selected, y_train)



RandomForestClassifier(random_state=42)

In [134]:


# Make predictions and evaluate the model
rf_model.predict(X_test_selected)


array(['Dell', 'Dell', 'Apple', 'Apple', 'Apple', 'Apple'], dtype=object)

In [135]:
from sklearn.feature_selection import SelectKBest,f_classif,chi2

In [136]:
X.shape

(30, 9)

In [137]:
X_new=SelectKBest(chi2,k=6).fit_transform(X,y)

In [138]:
X_new

array([[3.200e+01, 3.150e+05, 0.000e+00, 0.000e+00, 1.300e+01, 1.540e+01],
       [8.000e+00, 2.320e+05, 0.000e+00, 1.100e+01, 6.000e+00, 1.330e+01],
       [3.200e+01, 3.820e+05, 0.000e+00, 2.200e+01, 1.600e+01, 1.600e+01],
       [2.600e+01, 1.950e+05, 0.000e+00, 0.000e+00, 8.000e+00, 1.330e+01],
       [3.200e+01, 9.240e+04, 0.000e+00, 2.200e+01, 7.000e+00, 1.160e+01],
       [4.000e+00, 6.000e+04, 0.000e+00, 2.200e+01, 2.000e+00, 1.330e+01],
       [3.200e+01, 1.920e+05, 0.000e+00, 2.200e+01, 1.000e+00, 1.200e+01],
       [4.000e+00, 2.247e+05, 0.000e+00, 2.200e+01, 4.000e+00, 1.330e+01],
       [2.600e+01, 1.020e+05, 0.000e+00, 3.300e+01, 5.000e+00, 1.330e+01],
       [4.000e+00, 3.820e+05, 0.000e+00, 2.200e+01, 1.600e+01, 1.600e+01],
       [8.000e+00, 7.850e+04, 0.000e+00, 4.400e+01, 1.400e+01, 1.560e+01],
       [3.200e+01, 9.000e+04, 0.000e+00, 4.400e+01, 1.200e+01, 1.560e+01],
       [8.000e+00, 1.000e+05, 0.000e+00, 4.400e+01, 1.100e+01, 1.560e+01],
       [8.000e+00, 1.250e

In [139]:
X_new.shape

(30, 6)

In [140]:
pd.DataFrame(X_new)

0         1    2     3     4     5
0   32.0  315000.0  0.0   0.0  13.0  15.4
1    8.0  232000.0  0.0  11.0   6.0  13.3
2   32.0  382000.0  0.0  22.0  16.0  16.0
3   26.0  195000.0  0.0   0.0   8.0  13.3
4   32.0   92400.0  0.0  22.0   7.0  11.6
5    4.0   60000.0  0.0  22.0   2.0  13.3
6   32.0  192000.0  0.0  22.0   1.0  12.0
7    4.0  224700.0  0.0  22.0   4.0  13.3
8   26.0  102000.0  0.0  33.0   5.0  13.3
9    4.0  382000.0  0.0  22.0  16.0  16.0
10   8.0   78500.0  0.0  44.0  14.0  15.6
11  32.0   90000.0  0.0  44.0  12.0  15.6
12   8.0  100000.0  0.0  44.0  11.0  15.6
13   8.0  125000.0  1.0  22.0  14.0  15.6
14   8.0  122000.0  1.0  22.0  21.0  14.0
15  32.0  130000.0  1.0  22.0  15.0  15.6
16   4.0  185000.0  0.0  22.0   4.0  13.3
17  26.0  340000.0  0.0  22.0  17.0  17.0
18   8.0  224000.0  1.0  22.0   3.0  13.4
19  26.0  299000.0  0.0  44.0  19.0  15.6
20  26.0  132000.0  0.0  22.0  21.0  13.0
21   8.0  101000.0  0.0  22.0  21.0  11.0
22   8.0  200000.0  0.0  22.0  13.0  15.4
23   4.0  255000.0  0.0  22.0   8.0  13.3
24  26.0  140000.0  0.0  33.0   7.0  12.0
25   4.0  170000.0  0.0  44.0  18.0  15.6
26   4.0   25000.0  0.0  44.0  10.0  15.6
27   8.0   60000.0  0.0  44.0   9.0  15.6
28   8.0   33200.0  0.0  55.0  20.0  15.6
29  26.0   47000.0  0.0  44.0   0.0  12.5

In [141]:
feature_imp = SelectKBest(score_func=f_classif,k=6)

In [142]:
feature_imp.fit(X,y)

SelectKBest(k=6)

In [143]:
feature_imp.n_features_in_

9

In [144]:
feature_imp.scores_

array([ 0.95526839,  0.10623946,  0.72085106,  3.34309254,  0.06703176,
        5.09090909, 16.52682927,  1.23286244,  9.81595092])

In [145]:
df_imp=pd.DataFrame(feature_imp.scores_,columns=['scores'])

In [146]:
df_imp

scores
0   0.955268
1   0.106239
2   0.720851
3   3.343093
4   0.067032
5   5.090909
6  16.526829
7   1.232862
8   9.815951

In [150]:
df_score_features=pd.concat([df_imp,df_columns],axis=1)

In [149]:
df_columns=pd.DataFrame(df6.columns,columns=['features'])

In [151]:
df_score_features

scores             features
0   0.955268                Brand
1   0.106239               ItemID
2   0.720851              Ram(Gb)
3   3.343093          StoraGe(Gb)
4   0.067032            Price(Rs)
5   5.090909  Processorspeed(GHz)
6  16.526829                Touch
7   1.232862                Color
8   9.815951               Weight
9        NaN    DisplAysize(Inch)

In [152]:
df_score_features.nlargest(6,'scores')

scores             features
6  16.526829                Touch
8   9.815951               Weight
5   5.090909  Processorspeed(GHz)
3   3.343093          StoraGe(Gb)
7   1.232862                Color
0   0.955268                Brand